#!/bin/bash
# oclgrind (Oclgrind)
# Copyright (c) 2013-2014, James Price and Simon McIntosh-Smith,
# University of Bristol. All rights reserved.
#
# This program is provided under a three-clause BSD license. For full
# license terms please see the LICENSE file distributed with this
# source code.

function usage
{
  echo "Usage: "
  echo "  oclgrind [--dump-spir] [-i] COMMAND"
  echo "  oclgrind [--help | --version]"
  echo
  echo "Options:"
  echo "     --dump-spir     Dump SPIR to /tmp/oclgrind_*.{ll,bc}"
  echo "  -h --help          Display usage information"
  echo "  -i --interactive   Enable interactive mode"
  echo "  -v --version       Display version information"
  echo
  echo "For more information, please visit the Oclgrind wiki page:"
  echo "-> https://github.com/jrprice/Oclgrind/wiki"
  echo
}

# Parse arguments
while [ $# -gt 0 -a "${1:0:1}" == "-" ]
do
  if [ "$1" == "--dump-spir" ]
  then
    export OCLGRIND_DUMP_SPIR=1
  elif [ "$1" == "-h" -o "$1" == "--help" ]
  then
    usage
    exit 0
  elif [ "$1" == "-i" -o "$1" == "--interactive" ]
  then
    export OCLGRIND_INTERACTIVE=1
  elif [ "$1" == "-v" -o "$1" == "--version" ]
  then
    echo
    echo "Oclgrind __VERSION__"
    echo
    echo "Copyright (c) 2013-2014"
    echo "James Price and Simon McIntosh-Smith, University of Bristol"
    echo "https://github.com/jrprice/Oclgrind"
    echo
    exit 0
  else
    echo "Unrecognized argument '$1'"
    usage
    exit 1
  fi
  shift
done

# Ensure target command supplied
if [ $# -lt 1 ]
then
  usage
  exit 1
fi

# Inject liboclgrind.{so,dylib} and run command
if [ "$(uname -s)" == "Darwin" ]
then
  DYLD_INSERT_LIBRARIES=__ROOT__/lib/liboclgrind.dylib \
      DYLD_FORCE_FLAT_NAMESPACE=1 $@
else
  LD_PRELOAD=__ROOT__/lib/liboclgrind.so $@
fi
