#!/bin/bash

if [ $# -lt 1 ]
then
  echo "Usage: run_test SIMFILE [path/to/oclgrind-kernel]"
  exit 1
fi

SIM=${1##*/}
REF=${1%.sim}.ref
NAME=${SIM%.sim}
OUT=$NAME.out
DIFF=$NAME.diff
EXE=oclgrind-kernel
if [ "$AM_TESTS" == "1" ]
then
  EXE=$PWD/oclgrind-kernel
  OUT=tests/kernels/$NAME/$OUT
  DIFF=tests/kernels/$NAME/$DIFF
fi

(cd $(dirname $1); $EXE -g --data-races $SIM ) >$OUT 2>&1

RET=$?
cat $OUT
echo

if [ $RET -ne 0 ]
then
  echo "oclgrind-kernel returned non-zero value ($RET)"
  exit $RET
fi

REF_START=$(grep -n "Global Memory:" $REF | awk -F ':' '{print $1}')
OUT_DATA=$(grep -n "Global Memory:" $OUT | awk -F ':' '{print $1}')
if [ "$REF_START" == "" -o "$OUT_DATA" == "" ]
then
    echo "Global memory dump missing from output or reference"
    exit 1
fi

# Check that errors are reported if and only if they are expected
if [ $REF_START -ne 1 -a $OUT_DATA -eq 1 ]
then
    echo "Error expected, but no error reported"
    exit 1
elif [ $REF_START -eq 1 -a $OUT_DATA -ne 1 ]
then
    echo "Error reported, but no error expected"
    exit 1
fi

diff <(tail -n +$REF_START $REF) <(tail -n +$OUT_DATA $OUT) >$DIFF 2>&1
if [ -s $DIFF ]
then
  echo "Output didn't match reference"
  cat $DIFF
  exit 1
fi

echo
echo "Test passed."
