#!/bin/bash

if [ $# -lt 1 ]
then
  echo "Usage: run_test SIMFILE [path/to/oclgrind-kernel]"
  exit 1
fi

SIM=${1##*/}
REF=${1%.sim}.ref
NAME=${SIM%.sim}
OUT=$NAME.out
DIFF=$NAME.diff
EXE=oclgrind-kernel
if [ "$AM_TESTS" == "1" ]
then
  EXE=$PWD/oclgrind-kernel
  OUT=tests/kernels/$NAME/$OUT
  DIFF=tests/kernels/$NAME/$DIFF
fi

(cd $(dirname $1); $EXE -g $SIM ) >$OUT 2>&1

RET=$?
cat $OUT

if [ $RET -ne 0 ]
then
  echo "oclgrind-kernel returned non-zero value ($RET)"
  exit $RET
fi

diff $REF $OUT >$DIFF 2>&1
if [ -s $DIFF ]
then
  echo "Output didn't match reference"
  cat $DIFF
  exit 1
fi

echo
echo "Test passed."
