#!/bin/bash

NX=${1:-30}
NY=${2:-20}
ITR=${3:-10}

CELLS=`echo "$NX*$NY" | bc`
BUFSIZE=`echo $CELLS*4 | bc`
OUT="OUTPUT"
SIM="tmp.sim"

# Simulation constants
DENSITY=0.1
ACCEL=0.005
OMEGA=1.85
REYNOLDS_DIM=10
VISCOSITY=`echo "scale=16; (1.0 / 6.0 * (2.0 / $OMEGA - 1.0))" | bc`

# Generate initial OUTPUT with w0, w1 values
rm -rf $OUT
w0="89 88 08 3D"
w1="89 88 88 3C"
w1a="0F E6 89 3C"
w3a="03 2B 87 3C"
for i in `seq 1 $CELLS`
do
    echo $w0 >>$OUT
done
for i in `seq 1 $CELLS`
do
    echo >>$OUT
    echo >>$OUT
    echo >>$OUT
    echo >>$OUT
done
for y in `seq 1 $NY`
do
    echo $w1a >>$OUT
    for x in `seq 2 $NX`
    do
        echo $w1 >>$OUT
    done
done
for i in `seq 1 $CELLS`
do
    echo $w1 >>$OUT
done
for y in `seq 1 $NY`
do
    echo $w3a >>$OUT
    for x in `seq 2 $NX`
    do
        echo $w1 >>$OUT
    done
done
for i in `seq 1 $CELLS`
do
    echo $w1 >>$OUT
done

# Timestep loop
for i in `seq 1 $ITR`
do
    rm -f $SIM

    echo "tests/lb.s" >>$SIM
    echo "timestep" >>$SIM
    echo "$CELLS 1 1" >>$SIM
    echo "$CELLS 1 1" >>$SIM
    echo "" >>$SIM
    echo "s 4" >>$SIM
    hex=`printf "%08X\n" $NX`
    echo ${hex:6:2}" "${hex:4:2}" "${hex:2:2}" "${hex:0:2} >>$SIM
    echo "" >>$SIM
    echo "s 4" >>$SIM
    hex=`printf "%08X\n" $NY`
    echo ${hex:6:2}" "${hex:4:2}" "${hex:2:2}" "${hex:0:2} >>$SIM
    echo "" >>$SIM

    echo "b $BUFSIZE" >>$SIM
    head -n $CELLS $OUT >>$SIM
    echo "" >>$SIM

    echo "b $BUFSIZE" >>$SIM
    tail -n `echo "$CELLS*4" | bc` $OUT | head -n $CELLS >>$SIM
    echo "" >>$SIM

    echo "b $BUFSIZE" >>$SIM
    tail -n `echo "$CELLS*3" | bc` $OUT | head -n $CELLS >>$SIM
    echo "" >>$SIM

    echo "b $BUFSIZE" >>$SIM
    tail -n `echo "$CELLS*2" | bc` $OUT | head -n $CELLS >>$SIM
    echo "" >>$SIM

    echo "b $BUFSIZE" >>$SIM
    tail -n `echo "$CELLS*1" | bc` $OUT | head -n $CELLS >>$SIM
    echo "" >>$SIM

    echo "b $BUFSIZE" >>$SIM
    for i in `seq 1 $CELLS`
    do
        echo "00 00 00 00" >>$SIM
    done
    echo "" >>$SIM

    echo "b $BUFSIZE" >>$SIM
    for i in `seq 1 $CELLS`
    do
        echo "00 00 00 00" >>$SIM
    done
    echo "" >>$SIM

    echo "b $BUFSIZE" >>$SIM
    for i in `seq 1 $CELLS`
    do
        echo "00 00 00 00" >>$SIM
    done
    echo "" >>$SIM

    echo "b $BUFSIZE" >>$SIM
    for i in `seq 1 $CELLS`
    do
        echo "00 00 00 00" >>$SIM
    done
    echo "" >>$SIM

    echo "b 4" >>$SIM
    echo "00 00 00 00" >>$SIM
    echo "" >>$SIM

    echo "l $BUFSIZE" >>$SIM
    echo "" >>$SIM

    ./oclgrind $SIM -g >MEM
    if [ $? -ne 0 ]
    then
        echo "Error running oclgrind"
        cat MEM
        exit 1
    fi
    cat MEM \
        | grep -A `echo "$CELLS*9" | bc` "Global Memory" \
        | tail -n +2 \
        | awk '{$1="";print}' \
        >$OUT
done

# Compute reynolds number
hex=`tail -n 2 MEM | head -n 1 | awk '{print $5$4$3$2}'`
avg=`util/floatval $hex`
avg=`echo "scale=16; $avg / $CELLS" | bc`
echo "scale=8; ($avg * $REYNOLDS_DIM) / $VISCOSITY" | bc
