#!/bin/bash

SRC=$1
NAME=`echo $SRC | awk -F '/' '{print $NF}' | awk -F '.' '{print $1}'`

clang -cc1 -g -emit-llvm \
    -cl-kernel-arg-info -triple spir64-unknown-unknown \
    -o $NAME.s \
    $SRC

if [ $? -ne 0 ]
then
    exit
fi

clang -cc1 -g -emit-llvm-bc \
    -cl-kernel-arg-info -triple spir64-unknown-unknown \
    -o $NAME.bc \
    $SRC
