#!/bin/bash

SRC=$1
NAME=`echo $SRC | awk -F '/' '{print $NF}' | awk -F '.' '{print $1}'`

clang-3.2 -cc1 -g -O0 -emit-llvm -include clc.h \
    -cl-kernel-arg-info -triple spir64-unknown-unknown \
    -o $NAME.s \
    $SRC

if [ $? -ne 0 ]
then
    exit
fi

clang-3.2 -cc1 -g -O0 -emit-llvm-bc -include clc.h \
    -cl-kernel-arg-info -triple spir64-unknown-unknown \
    -o $NAME.bc \
    $SRC
